name: Trigger auto deployment for angular-jumpstart-ui

# When this action will be executed
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
    - main

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.ANGULARJUMPSTARTUI_REGISTRY_USERNAME }}
          password: ${{ secrets.ANGULARJUMPSTARTUI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: danwahlin/nginx-angular-jumpstart:${{ github.sha }}
          build-args: NG_APP_API_URL=${{ secrets.NG_APP_API_URL }}
          file: ./.docker/nginx.dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANGULARJUMPSTARTUI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n angular-jumpstart-ui -g Angular-Jumpstart-RG --server docker.io --username  ${{ secrets.ANGULARJUMPSTARTUI_REGISTRY_USERNAME }} --password ${{ secrets.ANGULARJUMPSTARTUI_REGISTRY_PASSWORD }}
            az containerapp update -n angular-jumpstart-ui -g Angular-Jumpstart-RG --image danwahlin/nginx-angular-jumpstart:${{ github.sha }}
